name: Python package

on:
  push:
    branches:
      master
  pull_request:

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.6.8, 3.9]

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        sudo apt-get update -y
        sudo apt-get install -y pycodestyle
    - name: Run pycodestyle
      run: |
        pycodestyle --max-line-length=99 --ignore=None check_structural_metadata.py
    - name: Run tests
      run: |
        python3 -m unittest -v
